name: Feature request
description: Something git why should do
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What are you trying to do that git why makes hard today?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What would you want it to do? Rough is fine.
    validations:
      required: true
